=== amitkmrghosh/spring/batch/spring-batch-master/spring-batch-infrastructure-tests/src/test/resources/org/springframework/batch/item/xml/domain/trade.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="urn:org.springframework.batch.io.oxm.domain" 
	xmlns:tns="urn:org.springframework.batch.io.oxm.domain" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

  <xs:element name="records">
  	<xs:complexType>
  		<xs:choice minOccurs="0" maxOccurs="1"><xs:element name="trades"/></xs:choice>
  	</xs:complexType>
  </xs:element>

  <xs:element name="trades">
  	<xs:complexType>
  		<xs:choice minOccurs="0" maxOccurs="unbounded"><xs:element name="trade" type="tns:trade"/></xs:choice>
  	</xs:complexType>
  </xs:element>

  <xs:element name="trade" type="tns:trade"/>

  <xs:complexType name="trade">
    <xs:sequence>
      <xs:element name="customer" type="xs:string" minOccurs="0"/>
      <xs:element name="isin" type="xs:string" minOccurs="0"/>
      <xs:element name="price" type="xs:decimal" minOccurs="0"/>
      <xs:element name="quantity" type="xs:long"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== amitkmrghosh/spring/batch/spring-batch-master/spring-batch-infrastructure-tests/src/test/resources/org/springframework/batch/item/xml/domain/trades.xml
<?xml version="1.0" encoding="UTF-8"?>
<trades xmlns="urn:org.springframework.batch.io.oxm.domain" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:org.springframework.batch.io.oxm.domain trade.xsd">
	<trade>
		<customer>Customer1</customer>
		<isin>XYZ0001</isin>
		<price>11.39</price>
		<quantity>5</quantity>
	</trade>
	<trade>
		<customer>Customer2</customer>
		<isin>XYZ0002</isin>
		<price>72.99</price>
		<quantity>2</quantity>
	</trade>
	<trade>
		<customer>Customer3</customer>
		<isin>XYZ0003</isin>
		<price>99.99</price>
		<quantity>9</quantity>
	</trade>
</trades>
